import {
  Context,
  getSheetIndex,
  indexToColumnChar,
  locale,
  sortSelection,
  SortRefusal,
} from "@fortune-sheet/core";
import React, {
  ChangeEvent,
  useCallback,
  useContext,
  useEffect,
  useId,
  useState,
} from "react";
import WorkbookContext from "../../context";
import "./index.css";
import { useDialog } from "../../hooks/useDialog";
import { useAlert } from "../../hooks/useAlert";
import { activateOnEnterOrSpace } from "../../utils/keyboardActivation";
import { announce } from "../../hooks/useContextMenuAnnouncements";
import { sortRefusalMessage } from "../../utils/sortRefusal";

type RadioChangeEvent = React.ChangeEvent<HTMLInputElement>;

type Props = {
  /**
   * Id for the heading that names this dialog, generated by the caller.
   *
   * It comes from outside because `showDialog`'s `labelledBy` has to be set at
   * the moment the dialog opens, which is before this component mounts — so the
   * id cannot originate here. The caller holds one `useId()` and gives the same
   * value to both.
   */
  titleId: string;
};

const CustomSort: React.FC<Props> = ({ titleId }) => {
  /*
   * Per instance, not module constants.
   *
   * These four ids were hardcoded, which is the same defect
   * `CONTEXT_MENU_REGION_ID_SUFFIX` documents at length for the status region:
   * ids are per *document*, this component is per *workbook*, and the
   * spreadsheet sim renders five workbooks on one page. The modal backdrop is
   * `position: absolute` inside its own workbook container rather than
   * viewport-fixed, so a second workbook's dialog can be opened while the first
   * is still up — and then an IDREF resolves to the first match in the
   * document. The second dialog announced the first one's range, its radios got
   * no name from their `<label>`, and pressing its "Ascending" text toggled the
   * other dialog's radio.
   *
   * Two of them (`fortune-sort-title`, `fortune-sort-haveheader`) were already
   * hardcoded before this change, but harmlessly: nothing referenced them. The
   * `htmlFor` associations and the live `aria-labelledby` are what turned inert
   * duplicate ids into cross-dialog mis-wiring.
   */
  const ascRadioId = useId();
  const descRadioId = useId();
  const hasHeaderCheckboxId = useId();
  // Not in the review comment's list of four, but the same defect and a live
  // `htmlFor` since before this change: the "Sort by" label and its select.
  const sortBySelectId = useId();
  const [rangeColChar, setRangeColChar] = useState<string[]>([]);
  const [ascOrDesc, setAscOrDesc] = useState(true);
  const { context, setContext } = useContext(WorkbookContext);
  const [selectedValue, setSelectedValue] = useState<string>("0");
  const [isTitleChange, setIstitleChange] = useState(false);
  const { sort } = locale(context);
  const { hideDialog } = useDialog();
  const { showAlert } = useAlert();

  /**
   * Why the last confirm refused, for the alert below.
   *
   * A ref rather than a local, because the recipe passed to `setContext` runs
   * during reconcile — anything assigned in it is not readable on the line
   * after the `setContext` call.
   */
  const refusalRef = React.useRef<SortRefusal | null>(null);

  const handleSortConfirm = useCallback(() => {
    refusalRef.current = null;
    setContext((draftCtx: Context) => {
      // The sort itself was silent. Opening this dialog announces the dialog,
      // and closing it returns focus to the grid — but nothing ever said the
      // data had been reordered, which is the one thing that actually changed
      // (WCAG 4.1.3). Reuses the results the menu's own sort rows announce.
      //
      // Gated on `sortSelection`'s outcome for the same reason those rows are:
      // it refuses silently on read-only, a null or multi-range selection, an
      // empty column and merged cells in the range. The `sort` row that opens
      // this dialog does not itself gate on multi-range, so an unguarded
      // announce here gave the full success choreography — message, dialog
      // close, focus restore — to a confirm that reordered nothing.
      //
      // Gating alone replaced a false claim with silence, though, and `Confirm`
      // closes the dialog either way: the user pressed Sort, the dialog went
      // away and nothing moved, with no message in either channel. So the
      // refusal reason is reported through the same alert the menu rows use.
      const outcome = sortSelection(
        draftCtx,
        ascOrDesc,
        parseInt(selectedValue, 10)
      );
      draftCtx.contextMenu = {};
      if (!outcome.sorted) {
        refusalRef.current = outcome.reason;
        return;
      }
      announce(
        draftCtx,
        ascOrDesc
          ? "rightclick.announceSortedAsc"
          : "rightclick.announceSortedDesc"
      );
    });
    hideDialog();
    // Deferred, and not showable from inside the recipe the way the cell
    // menu's sort rows do it. `hideDialog` and `showAlert` are the same modal
    // slot — `useDialog` and `useAlert` both go through `ModalContext` — so an
    // alert raised before the `hideDialog()` above is immediately closed by it.
    // The menu rows have no such conflict because nothing is being hidden.
    //
    // A macrotask, matching `focusAfterCommit`: the recipe has not run yet when
    // this line executes, so `refusalRef` is only readable after the commit.
    // Landing after `Dialog`'s own focus restore is also right — the alert is
    // the thing to read, so it should take focus last.
    setTimeout(() => {
      if (refusalRef.current == null) return;
      const message = sortRefusalMessage(context, refusalRef.current);
      refusalRef.current = null;
      showAlert(message, "ok");
    });
  }, [ascOrDesc, context, hideDialog, selectedValue, setContext, showAlert]);

  const col_start = context.luckysheet_select_save![0].column[0];
  const col_end = context.luckysheet_select_save![0].column[1];
  const row_start = context.luckysheet_select_save![0].row[0];
  const row_end = context.luckysheet_select_save![0].row[1];
  const startCell = `${indexToColumnChar(col_start)}${row_start + 1}`;
  const endCell = `${indexToColumnChar(col_end)}${row_end + 1}`;

  const sheetIndex = getSheetIndex(context, context.currentSheetId) as number;

  const handleSelectChange = (event: ChangeEvent<HTMLSelectElement>) => {
    setSelectedValue(event.target.value);
  };

  // 改变排序方式
  const handleRadioChange = useCallback((e: RadioChangeEvent) => {
    const sortValue = e.target.value;
    setAscOrDesc(sortValue === "asc");
  }, []);

  const handleTitleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const value = e.target.checked;
      setIstitleChange(value);
    },
    []
  );

  // 获取排序列
  useEffect(() => {
    const list: string[] = [];
    if (isTitleChange) {
      for (let i = col_start; i <= col_end; i += 1) {
        // 判断列首是否为空
        const cell = context.luckysheetfile[sheetIndex].data?.[row_start]?.[i];
        const colHeaderValue = cell?.m || cell?.v;
        if (colHeaderValue) {
          list.push(colHeaderValue as string);
        } else {
          const ColumnChar = indexToColumnChar(i);
          list.push(`${sort.columnOperation} ${ColumnChar}`);
        }
      }
    } else {
      for (let i = col_start; i <= col_end; i += 1) {
        const ColumnChar = indexToColumnChar(i);
        list.push(ColumnChar);
      }
    }
    setRangeColChar(list);
  }, [
    col_end,
    col_start,
    context.luckysheetfile,
    isTitleChange,
    row_start,
    sheetIndex,
    sort.columnOperation,
  ]);

  return (
    <div className="fortune-sort">
      <div className="fortune-sort-title">
        {/*
          The spaces are real text nodes, and they are load-bearing rather than
          formatting. This element is the dialog's accessible name via
          `aria-labelledby`, and name computation concatenates descendant text
          while ignoring CSS — so while the gaps came only from a `margin: 0 4px`
          on the cell references, the name computed as "Sort range fromF4toH6"
          and VoiceOver read it as one run-together word. That margin is gone, so
          the visible gap and the spoken gap now come from the same source.
        */}
        <span id={titleId}>
          {sort.sortRangeTitle} {startCell} {sort.sortRangeTitleTo} {endCell}
        </span>
      </div>

      <div>
        <div className="fortune-sort-modal">
          {/*
            The text beside each control was a bare <span>, so none of this
            dialog's three inputs had an accessible name (WCAG 4.1.2) — a screen
            reader announced "checkbox" and "radio button" and nothing else. A
            real <label> rather than aria-label, because the text is already on
            screen: associating it also makes the words a click target.
          */}
          <div>
            <input
              type="checkbox"
              id={hasHeaderCheckboxId}
              onChange={handleTitleChange}
            />
            <label htmlFor={hasHeaderCheckboxId}>{sort.hasTitle}</label>
          </div>

          <div className="fortune-sort-tablec">
            <table cellSpacing="0">
              <tbody>
                <tr>
                  <td style={{ width: "190px" }}>
                    <label htmlFor={sortBySelectId}>{sort.sortBy}</label>
                    <select
                      id={sortBySelectId}
                      name="sort_0"
                      className="fortune-sort-by-select"
                      onChange={handleSelectChange}
                    >
                      {rangeColChar.map((col, index) => {
                        return (
                          <option value={index} key={index}>
                            {col}
                          </option>
                        );
                      })}
                    </select>
                  </td>
                  <td>
                    <div>
                      <input
                        type="radio"
                        id={ascRadioId}
                        value="asc"
                        defaultChecked
                        name="sort_0"
                        onChange={handleRadioChange}
                      />
                      <label htmlFor={ascRadioId}>{sort.asc}</label>
                    </div>
                    <div>
                      <input
                        type="radio"
                        id={descRadioId}
                        value="desc"
                        name="sort_0"
                        onChange={handleRadioChange}
                      />
                      <label htmlFor={descRadioId}>{sort.desc}</label>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div className="fortune-sort-button">
        <div
          className="button-basic button-primary"
          onClick={handleSortConfirm}
          onKeyDown={activateOnEnterOrSpace}
          tabIndex={0}
          role="button"
        >
          {sort.confirm}
        </div>
      </div>
    </div>
  );
};

export default CustomSort;
